# Top-level settings for Workers
compatibility_date = "2024-06-01"
compatibility_flags = ["nodejs_compat"]
account_id = "c84e7a9bf7ed99cb41b8e73566568c75"

# Worker specific configuration for hol.is
[env.production]
name = "hol-is" 
main = "chus.me/src/index.ts"
kv_namespaces = [
  { binding = "INVITES", id = "57a39408dd6e4fbc91ae423b82293f43", preview_id = "6c947cbd83314bb1b648ea309a6e9854" }
]

# Worker configuration for holis.social
[env.production_social]
name = "holis-social"
main = "chusme.social/src/index.ts"